apiVersion: 1

datasources:
  - name: Prometheus
    uid: prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true

  - name: CloudWatch
    uid: cloudwatch
    type: cloudwatch
    jsonData:
      authType: keys
      defaultRegion: $AWS_REGION
    secureJsonData:
      accessKey: $AWS_ACCESS_KEY_ID
      secretKey: $AWS_SECRET_ACCESS_KEY
